parameters:
    knp_last_tweets.last_tweets_fetcher.api.class: Knp\Bundle\LastTweetsBundle\Twitter\LastTweetsFetcher\ApiFetcher

services:
     api_browser:
         alias: buzz

     knp_last_tweets.last_tweets_fetcher.api:
         class: %knp_last_tweets.last_tweets_fetcher.api.class%
         arguments:
             - "@api_browser"
