imports:
  - { resource: api.yml }
  - { resource: oauth.yml }

parameters:
    knp_last_tweets.last_tweets_fetcher.zend_cache.class: Knp\Bundle\LastTweetsBundle\Twitter\LastTweetsFetcher\ZendCacheFetcher
    knp_last_tweets.last_tweets_fetcher.zend_cache.cache_name: knp_last_tweets

services:
    knp_last_tweets.last_tweets_fetcher.zend_cache:
        class: %knp_last_tweets.last_tweets_fetcher.zend_cache.class%
        arguments:
            - @knp_last_tweets.last_tweets_secondary_fetcher
            - @knp_zend_cache.manager
            - %knp_last_tweets.last_tweets_fetcher.zend_cache.cache_name%
